name: Genesa Leadership
favicon: null
layout_spectrum: 0.01803
typography_spectrum: 0.9249578
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#291E33'
    - '#39BFB0'
    - '#E5F3E9'
    - '#F4D13A'
    - '#C2B59B'
  brandStrength: 0.01180438
  lightness: 0.1273187
  saturation: 0.8340425
  rhythmicContrast: 0.4595745
purpose: []
