name: Genesa Leadership
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3425532
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#84ffa4'
    - '#8df6fc'
    - '#ffffff'
    - '#e6c0fe'
    - '#faa0ff'
  brandStrength: 0.8425532
  lightness: 0.125
  saturation: 0.05744681
  rhythmicContrast: 1
purpose: []
