analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.8340425
  brandStrength: 0.8425532
  lightness: 0.7344013
  brandColors:
    - '#382F28'
    - '#D8CFC5'
    - '#CD985D'
    - '#9B9188'
    - '#776F6E'
  rhythmicContrast: 0.4595745
typography_spectrum: 0.6595744
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: Genesa Leadership
