favicon: null
name: Genesa Leadership
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7310287
  brandStrength: 0.8425532
  lightness: 0.7150084
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  rhythmicContrast: 0.3829787
typography_spectrum: 0.3425532
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.53457
analytics:
  twitter: null
  google: null
  facebook: null
